[package]
name = "localstack-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = "0.5.1"
serde_json = { version = "1.0.140", features = ["raw_value"] }
reqwest = { version = "0.12.22", features = ["blocking"] }
serde = { version = "1.0.219" }
tera = { version = "1.20.0" }
rust-embed = { version = "8.7.2" }
walkdir = { version = "2.5.0" }
notify = { version = "8.1.0" }
