name: Build Image and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "trunk"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "trunk"
    tags-ignore:
      - "*"

concurrency:
  group: docker-biad-${{ github.ref }}
  cancel-in-progress: true

env:
  SYSDIG_SECURE_ENDPOINT: "https://us2.app.sysdig.com"

jobs:
  prep:
    if: github.repository_owner == 'ideacrew' && ((github.event_name == 'push') || (github.event_name == 'workflow_dispatch') || (github.event.pull_request.head.repo.owner.login == 'ideacrew'))
    runs-on: ubuntu-latest
    outputs:
      imageName: ${{ steps.prep.outputs.image_name }}
      tagName: ${{ steps.prep.outputs.tag_name }}
      taggedImage: ${{ steps.prep.outputs.tagged_image }}
      repositoryName: ${{ steps.prep.outputs.repository_name }}
      registryGhcr: ${{ steps.prep.outputs.registry_ghcr }}
    steps:
      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1
      - name: Prepare info
        id: prep
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | head -c7)
          REPO=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
          TAG=${{ env.GIT_BRANCH_NAME }}-$(echo $GITHUB_SHA | head -c7)
          IMAGE=ideacrew/$REPO
          echo "image_name=${IMAGE}" >> $GITHUB_OUTPUT
          echo "tag_name=${TAG}" >> $GITHUB_OUTPUT
          echo "tagged_image=${IMAGE}:${TAG}" >> $GITHUB_OUTPUT
          echo "repository_name=$REPO" >> $GITHUB_OUTPUT
          echo "registry_ghcr=ghcr.io" >> $GITHUB_OUTPUT

  # Uses buildx to build and push the image
  build-and-upload-image:
    needs: [prep]
    runs-on: ubuntu-latest
    steps:
      # Check out repository
      - uses: actions/checkout@v2
      - name: Build Image
        uses: ./.github/actions/build_image
        id: build-docker-image
        with:
          dockerFile: ".docker/production/Dockerfile"
          baseImageName: ${{ needs.prep.outputs.imageName }}
          tagName: ${{ needs.prep.outputs.tagName }}
          pushImage: ${{ github.event_name != 'pull_request' }}
          loadImage: ${{ github.event_name == 'pull_request' }}
          ghcrUsername: ${{ github.actor }}
          ghcrPassword: ${{ secrets.GITHUB_TOKEN }}
          pushLatest: true
      - name: Scan docker image
        if: github.event_name != 'pull_request'
        id: scan
        uses: anchore/scan-action@main
        with:
          image: ${{ steps.build-docker-image.outputs.imageLocation }}
          acs-report-enable: true
          fail-build: false
          severity-cutoff: critical
      - name: Scan the image with Sysdig
        uses: ./.github/actions/run_sysdig
        if: ${{ github.event_name != 'pull_request' }}
        with:
          imageLocation: ${{ steps.build-docker-image.outputs.imageLocation }}
          sysdigApiToken: ${{ secrets.SECURE_API_TOKEN }}
