name: Quality Workbench
on:
  push:
  workflow_dispatch:

concurrency:
  group: qwb-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          cargo test
  test-compile-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Attempt Release Compilation
        run: |
          cargo build --release
